export const ADD_ITEM_BLOCK = " ADD_ITEM_BLOCK";
export const ADD_ITEM_TO_BLOCK = " ADD_ITEM_TO_BLOCK";
export const ADD_ITEM_SET = "ADD_ITEM_SET";
export const DELETE_ITEM_FROM_BLOCK = "DELETE_ITEM_FROM_BLOCK";
export const DELETE_BLOCK_FROM_SET = "DELETE_BLOCK_FROM_SET";
export const SAVE_ITEM_SET = "SAVE_ITEM_SET";